# Generated by Django 3.1.4 on 2020-12-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_category_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
